### ISSUE TITLE
Separation from Core

### ISSUE THREAD

**Issue by erikerikson** [shoreditch-ops/artillery#271]
One of the strengths we have enjoyed in this tool is the separation between the UX and the execution core.  This makes for a clean and flexible means of defining the capability and the interaction separately.  It also allows for more flexible uses of the library.

However, there are [two violations of this pattern](https://github.com/shoreditch-ops/artillery/blob/master/lib/worker.js#L66).  Both the `opts.script.config.processor` and `opts.script.config.files` attributes are pre-loaded in the `artillery` cli module rather than in `artillery-core`.  I hope I'm not rehashing old conversations and we respect your skill so I'm wondering: can you help me understand why this factoring decision was made?

For reference, this comes up due to [a PR we received on serverless-artillery](https://github.com/Nordstrom/serverless-artillery/pull/65) to add that pre-processing.  Long term, this will create a cat and mouse chase that you can probably imagine we'd like to avoid.

Thanks!

**Comment by hassy** [comment]
Core is meant to be decoupled from the environment it's running in, hence the avoidance of FS operations inside it for example. Files being loaded elsewhere is actually the consequence of the intention that led to core being separate from the CLI in the first place.

The separation between `artillery-core` and `artillery` has become somewhat arbitrary anyway as Artillery has evolved. For example, Artillery has multicore support now but it's implemented in the `artillery` package rather than `artillery-core` even though the argument could be made for implementing it in there.

Going forward we'd probably want to look at breaking `artillery-core` apart into a few smaller and more focused modules or rolling everything into one package to make managing changes, testing, and publishing easier.

**Comment by erikerikson** [comment]
This definitely helps me understand, thanks @hassy!

We would definitely be advocates for moving that into a reusable core module at some point.  Is there a means by which we could be more proactively aware of this sort of additional capability in the future?

**Comment by hassy** [comment]
[Changelogs](https://github.com/shoreditch-ops/artillery/releases) would be the way to stay abreast of new features.
