### ISSUE TITLE
Feature: default processor functions for each request

### ISSUE THREAD

**Issue by ericmacfa** [shoreditch-ops/artillery#330]
Title says it all. Pre and post feature gists below.

### Pre-feature
```js
config:
  processor: './request-utils.js'
scenarios:
  - name: 'Example scenario'
    flow:
    - get:
        url: /dashboard
        beforeRequest: injectCustomData
        afterResponse: logRequestRun
    - get:
        url: /api/users
        beforeRequest: injectCustomData
        afterResponse: logRequestRun
    - get:
        url: /api/profile
        beforeRequest: injectCustomData
        afterResponse: logRequestRun
    - get:
        url: /api/groups
        beforeRequest: injectCustomData
        afterResponse: logRequestRun
    - get:
        url: /api/feeds
        beforeRequest: injectCustomData
        afterResponse: logRequestRun
```

### Post feature
```js
config:
  processor: './request-utils.js'
  defaults:
    beforeRequest: [injectCustomData]
    afterResponse: [logRequestRun]
scenarios:
  - name: 'Example scenario'
    flow:
    - get:
        url: /dashboard
    - get:
        url: /api/users
    - get:
        url: /api/profile
    - get:
        url: /api/groups
    - get:
        url: /api/feeds
```

**Comment by hassy** [comment]
Already supported - you can set `beforeRequest` & `afterResponse` properties on a scenario. :)

https://artillery.io/docs/testing_http.html#setting-scenario-level-hooks

**Comment by jordan-brough** [comment]
FYI the link above has changed to:
https://artillery.io/docs/http-reference/#setting-scenario-level-hooks

@hassy is this available at the config level also?  (I tried it in `config` and it didn't seem to work.)  E.g. I'd like to set an `x-request-id` header before every single request so that I can connect my artillery debug logs with my application logs.

**Comment by hassy** [comment]
@jordan-brough No, there's no way to set that in the `config` section at the moment, but it's possible to set a hook for an entire scenario (so that it's applied to every request):

```yaml
scenarios:
  - beforeRequest: "setHeaders"
    flow:
        - get:
            url: "/"
        # more requests
```

That will invoke `setHeaders` for each request (and before any `beforeRequest` hooks specified for individual requests).
