### ISSUE TITLE
Loading a list from a CSV file

### ISSUE THREAD

**Issue by Vysarat** [shoreditch-ops/artillery#366]
I'm trying to test a POST API that takes a request with JSON in the body. One of the values is a list, so the request looks like this:
```
{
    "myList" : [ "item1", "item2", "item3"],
    "otherVar" : "foo"
}
```
I want to load the contents of the list (which can be of variable length) from a payload file, but I can't figure out the proper syntax. I need to escape the commas and double quotes, and the closest I've come so far is with this in my yml:
```
- post:
    json:
      myList: ["{{listVar}}"]
      otherVar: "foo"
```
But no matter how I structure my payload file, either the items in the list are treated as a single item, or the result isn't valid JSON.
I can get it to work by using a fixed length list, with a separate variable for each item, but I'd like to find a way to use variable length lists.

What's the right way to do this?

**Comment by hassy** [comment]
There's a couple of ways - you can set the payload with the `body` attribute rather than JSON (making sure that the JSON is properly escaped in the CSV file) or set the payload in a `beforeRequest` hook.

(At the moment Artillery assumes that all variables are strings. We're planning on addressing that at some point but it will require some pretty big changes and there's not ETA for it yet.)

**Comment by hassy** [comment]
Closing for now but feel free to reopen if you have further questions.
