### ISSUE TITLE
Only execute a request if custom condition is true

### ISSUE THREAD

**Issue by oleschaper** [shoreditch-ops/artillery#411]
This is kind of a "Help wanted" post.

I would like to execute a post requests inside a loop only if a condition is met.

The beforeRequest function seemed like the way to go but there is no way to call something like "skip" instead of "next" or is there?

Any other way to do this?

**Comment by oleschaper** [comment]
Nobody?

**Comment by hassy** [comment]
There's an undocumented `ifTrue` option:

```yaml
- get:
    url: "/"
    ifTrue: "someVar"
```

that will tell Artillery to only execute that request if `someVar` variable is set to a value.

Since it's undocumented there are no guarantees this feature won't be removed in future, however if it is, there will be a way to achieve the same result by other means.

**Comment by oleschaper** [comment]
Awesome, I will try that.
Thank you so much!
