### ISSUE TITLE
Large response body

### ISSUE THREAD

**Issue by Aslesha07** [shoreditch-ops/artillery#518]
Hi guys
I am running a scenario that runs a request which downloads a file which could potentially be very large. Looks like artillery uses request library under the hood to make the requests and it buffers the response, and there are limitations to the size of the Buffer

The exact error I'm seeing is `RangeError: "size" argument must not be larger than ...` (https://nodejs.org/api/buffer.html#buffer_buffer_constants_max_length)

I would like to stream the response to a file which hopefully will solve my problem. 
But I'm not sure if there is a hook I can use to do this? there is a `afterResponse` hook which from understanding is called after the response finishes.

Any help is appreciated. Thank you!

**Comment by hassy** [comment]
Hi @Aslesha07. We've recently identified a regression which causes Artillery to try to load the entire response into memory regardless of whether it's required or not (e.g. when there's no `capture` defined on the request). This will be fixed in the next release of Artillery.

Would that solve your issue or do you actually need to be able to be able to stream (and process) the response?

**Comment by Aslesha07** [comment]
Not loading the response into memory will definitely get rid of the error I'm seeing, so that'll definitely be super helpful.
But it would've been nicer if I could save the response to the file (stream it to the file so I don't run into any memory issues) since I have another script that verifies that the file is valid.

Thanks for your response :)
