### ISSUE TITLE
Regexp capture does not work with capturing groups

### ISSUE THREAD

**Issue by jamesfiltness** [shoreditch-ops/artillery#94]
When using the regexp capture with a regex that has a capturing group the captured match is not returned:

```
"capture": {
   "regexp": "<input name=\"someinput\" type=\"text\" value=\"(.*?)\" ",
   "as": "someinput"
}
```
Above, the string ("<input name=\"someinput\" type=\"text\" value=...") is returned as the only match, when what I really want is the match from the capturing group.

In **engine_http.js** the first match from the regex is always returned, which is the matched string itself:

```
  if (match[0]) {
    return match[0];
```

match[1] contains the result from the capturing group. Perhaps some mechanism to allow you to specify which array index of the regex result you want to return? ...

```
"capture": {
   "regexp": "<input name=\"someinput\" type=\"text\" value=\"(.*?)\" ",\,
   "regexResult": 1,
   "as": "someinput"
}
```

**Comment by hassy** [comment]
Yes 👍  A PR would be awesome (patch `engine_http.js` + a simple test case), with `group` instead of `regexpResult` perhaps. :)

**Comment by hassy** [comment]
Added in https://github.com/shoreditch-ops/artillery-core/pull/51

**Comment by nimo420ashish** [comment]
Hi,
I m also facing one issue regarding regexp.
I have to capture one value from the one api response, i m getting response also value is being captured  as id:

"capture": {
   "regexp":  " \"sid\":"(.+?)\"  "
   "as": "id"
}
Here this captured value should be this part (.+?) Only but instead of this part it's capturing whole regexp expression which would look like

\"sid\":"wsidio1ekfkfo4oro\"
Plz help me on this issue also othere capturing methods are not working even with json i m not able to capture.
